# Generated by Django 4.2.4 on 2024-04-21 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2024)]),
            preserve_default=False,
        ),
    ]
