# Generated by Django 4.2.4 on 2024-05-13 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldevice',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='simple_app.category'),
        ),
        migrations.AlterField(
            model_name='modeldevice',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Название модели'),
            preserve_default=False,
        ),
    ]
