# Generated by Django 4.2.4 on 2024-04-21 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0002_device_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
