# Generated by Django 4.2.4 on 2024-04-21 13:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0003_alter_device_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadPhone',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_app.device')),
                ('acoustic_design', models.CharField(choices=[('Закрытое', 'Closed'), ('Открытое', 'Open'), ('Полуоткрытое', 'Half-open')], max_length=20)),
                ('lower_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Нижняя граница Гц')),
                ('upper_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(20000), django.core.validators.MaxValueValidator(50000)], verbose_name='Верхняя Граница Гц')),
                ('active_noise_cancellation', models.BooleanField(default=False, verbose_name='Активное шумоподовление')),
            ],
            options={
                'verbose_name': 'Наушники',
                'verbose_name_plural': 'Наушники',
            },
            bases=('simple_app.device',),
        ),
        migrations.AddField(
            model_name='device',
            name='bluetoth',
            field=models.FloatField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(3.0), django.core.validators.MaxValueValidator(5.5)]),
            preserve_default=False,
        ),
    ]
