# Generated by Django 4.2.4 on 2024-05-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0003_remove_modeldevice_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldevice',
            name='cat',
            field=models.ManyToManyField(null=True, to='simple_app.category'),
        ),
    ]
