# Generated by Django 4.2.4 on 2024-05-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0004_modeldevice_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldevice',
            name='cat',
            field=models.ManyToManyField(to='simple_app.category'),
        ),
    ]
