# Generated by Django 4.2.4 on 2024-04-21 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0005_alter_menu_options_alter_headphone_acoustic_design_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='bluetoth',
            field=models.FloatField(default=4.0, validators=[django.core.validators.MinValueValidator(3.0), django.core.validators.MaxValueValidator(5.5)]),
        ),
    ]
