# Generated by Django 4.2.11 on 2024-06-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0005_alter_modeldevice_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeldevice',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='device',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='modeldevice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название производителя'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='TemplateForLinks',
        ),
    ]
