# Generated by Django 4.2.4 on 2024-04-21 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0006_alter_device_bluetoth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='bluetoth',
            field=models.FloatField(default=4.0, validators=[django.core.validators.MinValueValidator(3.0), django.core.validators.MaxValueValidator(5.5)], verbose_name='Bluetoth'),
        ),
        migrations.AlterField(
            model_name='device',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='device',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2024)], verbose_name='Год выпуска'),
        ),
    ]
